/**
 * src/constants.js
 * Shared default configurations and constants for filedrop.
 */

const DEFAULT_TIMEOUT_SECONDS = 300;
const DEFAULT_TRANSFER_TIMEOUT_SECONDS = 60;
const DEFAULT_SHUTDOWN_GRACE_MS = 10000;
const DEFAULT_SHUTDOWN_TIMEOUT_MS = 3000;
const DEFAULT_RATE_LIMIT_WINDOW_MS = 10000;
const DEFAULT_RATE_LIMIT_MAX = 30;
const DEFAULT_MAX_CONNECTIONS = 10;
const DEFAULT_ICE_TIMEOUT_SECONDS = 8;
const DEFAULT_MDNS_TIMEOUT_MS = 1000;

module.exports = {
  DEFAULT_TIMEOUT_SECONDS,
  DEFAULT_TRANSFER_TIMEOUT_SECONDS,
  DEFAULT_SHUTDOWN_GRACE_MS,
  DEFAULT_SHUTDOWN_TIMEOUT_MS,
  DEFAULT_RATE_LIMIT_WINDOW_MS,
  DEFAULT_RATE_LIMIT_MAX,
  DEFAULT_MAX_CONNECTIONS,
  DEFAULT_ICE_TIMEOUT_SECONDS,
  DEFAULT_MDNS_TIMEOUT_MS
};
